export const tablesReadme = `# Table Blocks

Create, format, and interact with rich multi-column tables directly within your notes.

---

## Features

- **Google Docs-Style Grid Picker**: Type \`/table\` or \`/\` in the editor to visually pick table dimensions with a live hover preview up to 10×8 cells.
- **AI & Markdown Interoperability**: Seamlessly renders GitHub Flavored Markdown (GFM) tables generated by AI assistants (e.g. Gemini, ChatGPT, Claude) or pasted from external sources.
- **Interactive Column Resizing**: Grab and drag any column boundary to customize width.
- **Smart Keyboard Navigation**:
  - \`Tab\`: Navigate to the next cell.
  - \`Shift + Tab\`: Navigate to the previous cell.
  - \`Tab\` at the last cell of the last row: Automatically creates and enters a new row.
- **Contextual Actions & Floating Bar**: Quick action toolbar for inserting rows above/below, columns left/right, deleting rows/columns, and toggling header rows.

---

## Usage

1. In any note, type \`/table\` and press \`Enter\` (or choose your desired dimensions on the visual grid).
2. Type text into the header cells and data cells.
3. Your tables are automatically serialized to standard Markdown in your vault for 100% portability.
`;
