/**
 * Comprehensive, high-performance emoji catalog for Flint.
 * Includes character, canonical name, hex code points, category, and search keywords.
 */

export type EmojiCategory =
  | 'Smileys & Emotion'
  | 'People & Body'
  | 'Animals & Nature'
  | 'Food & Drink'
  | 'Travel & Places'
  | 'Activities'
  | 'Objects'
  | 'Symbols'
  | 'Flags';

export interface EmojiDefinition {
  char: string;
  name: string;
  hex: string;
  category: EmojiCategory;
  keywords: string[];
}

/**
 * Converts a Unicode emoji string into a CDN-compatible hyphenated hex code point string.
 * Strips variation selector-16 (fe0f) for compatibility with Twemoji, Apple, and Google CDNs.
 */
export function emojiToHex(emoji: string): string {
  const codePoints: string[] = [];
  for (const codePoint of emoji) {
    const cp = codePoint.codePointAt(0);
    if (cp && cp !== 0xfe0f && cp !== 0xfe0e) {
      codePoints.push(cp.toString(16).toLowerCase());
    }
  }
  return codePoints.join('-');
}

/**
 * Converts a Unicode emoji string into a raw hyphenated hex code point string,
 * preserving variation selector-16 (fe0f) for compatibility with Apple and WhatsApp CDNs.
 */
export function emojiToRawHex(emoji: string): string {
  const codePoints: string[] = [];
  for (const codePoint of emoji) {
    const cp = codePoint.codePointAt(0);
    if (cp) {
      codePoints.push(cp.toString(16).toLowerCase());
    }
  }
  return codePoints.join('-');
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  'Smileys & Emotion',
  'People & Body',
  'Animals & Nature',
  'Food & Drink',
  'Travel & Places',
  'Activities',
  'Objects',
  'Symbols',
  'Flags',
];

// Helper to construct definitions quickly
function e(char: string, name: string, category: EmojiCategory, extraKeywords: string[] = []): EmojiDefinition {
  const hex = emojiToHex(char);
  const words = name.toLowerCase().split(/\s+/);
  return {
    char,
    name,
    hex,
    category,
    keywords: Array.from(new Set([...words, ...extraKeywords.map((k) => k.toLowerCase())])),
  };
}

export const EMOJI_CATALOG: EmojiDefinition[] = [
  // ── Smileys & Emotion ──
  e('😀', 'Grinning Face', 'Smileys & Emotion', ['happy', 'smile', 'joy']),
  e('😃', 'Grinning Face with Big Eyes', 'Smileys & Emotion', ['happy', 'joy']),
  e('😄', 'Grinning Face with Smiling Eyes', 'Smileys & Emotion', ['happy', 'laugh']),
  e('😁', 'Beaming Face with Smiling Eyes', 'Smileys & Emotion', ['smile', 'grin']),
  e('😆', 'Grinning Squinting Face', 'Smileys & Emotion', ['laugh', 'lol', 'haha']),
  e('😅', 'Grinning Face with Sweat', 'Smileys & Emotion', ['relief', 'nervous', 'hot']),
  e('🤣', 'Rolling on the Floor Laughing', 'Smileys & Emotion', ['rofl', 'lol', 'laugh']),
  e('😂', 'Face with Tears of Joy', 'Smileys & Emotion', ['cry', 'tears', 'laugh', 'lol']),
  e('🙂', 'Slightly Smiling Face', 'Smileys & Emotion', ['smile', 'calm']),
  e('🙃', 'Upside-Down Face', 'Smileys & Emotion', ['silly', 'sarcasm']),
  e('🫠', 'Melting Face', 'Smileys & Emotion', ['melt', 'hot', 'awkward']),
  e('😉', 'Winking Face', 'Smileys & Emotion', ['wink', 'flirt']),
  e('😊', 'Smiling Face with Smiling Eyes', 'Smileys & Emotion', ['blush', 'warm']),
  e('😇', 'Smiling Face with Halo', 'Smileys & Emotion', ['angel', 'innocent']),
  e('🥰', 'Smiling Face with Hearts', 'Smileys & Emotion', ['love', 'crush', 'adore']),
  e('😍', 'Smiling Face with Heart-Eyes', 'Smileys & Emotion', ['love', 'eyes', 'crush']),
  e('🤩', 'Star-Struck', 'Smileys & Emotion', ['star', 'eyes', 'excited', 'wow']),
  e('😘', 'Face Blowing a Kiss', 'Smileys & Emotion', ['kiss', 'love', 'flirt']),
  e('😋', 'Face Savoring Food', 'Smileys & Emotion', ['delicious', 'yum', 'taste']),
  e('😛', 'Face with Tongue', 'Smileys & Emotion', ['playful', 'silly']),
  e('😜', 'Winking Face with Tongue', 'Smileys & Emotion', ['crazy', 'joke']),
  e('🤪', 'Zany Face', 'Smileys & Emotion', ['crazy', 'goofy']),
  e('😝', 'Squinting Face with Tongue', 'Smileys & Emotion', ['playful']),
  e('🤑', 'Money-Mouth Face', 'Smileys & Emotion', ['cash', 'rich', 'dollar']),
  e('🤗', 'Smiling Face with Open Hands', 'Smileys & Emotion', ['hug', 'embrace']),
  e('🤭', 'Face with Hand Over Mouth', 'Smileys & Emotion', ['oops', 'giggle']),
  e('🫢', 'Face with Open Eyes and Hand Over Mouth', 'Smileys & Emotion', ['shock', 'gasp']),
  e('🫣', 'Face with Peeking Eye', 'Smileys & Emotion', ['scared', 'peek']),
  e('🤫', 'Shushing Face', 'Smileys & Emotion', ['quiet', 'secret', 'shh']),
  e('🤔', 'Thinking Face', 'Smileys & Emotion', ['ponder', 'consider', 'hmm']),
  e('🫡', 'Saluting Face', 'Smileys & Emotion', ['respect', 'salute', 'yes']),
  e('🤐', 'Zipper-Mouth Face', 'Smileys & Emotion', ['silent', 'secret']),
  e('🤨', 'Face with Raised Eyebrow', 'Smileys & Emotion', ['skeptic', 'doubt']),
  e('😐', 'Neutral Face', 'Smileys & Emotion', ['meh', 'indifferent']),
  e('😑', 'Expressionless Face', 'Smileys & Emotion', ['blank', 'unimpressed']),
  e('😶', 'Face Without Mouth', 'Smileys & Emotion', ['speechless', 'silent']),
  e('😏', 'Smirking Face', 'Smileys & Emotion', ['smug', 'flirt']),
  e('😒', 'Unamused Face', 'Smileys & Emotion', ['annoyed', 'grumpy']),
  e('🙄', 'Face with Rolling Eyes', 'Smileys & Emotion', ['eyeroll', 'whatever']),
  e('😬', 'Grimacing Face', 'Smileys & Emotion', ['awkward', 'eek', 'nervous']),
  e('🤥', 'Lying Face', 'Smileys & Emotion', ['pinocchio', 'lie']),
  e('😌', 'Relieved Face', 'Smileys & Emotion', ['peace', 'calm', 'zen']),
  e('😔', 'Pensive Face', 'Smileys & Emotion', ['sad', 'down']),
  e('😪', 'Sleepy Face', 'Smileys & Emotion', ['tired', 'sleep']),
  e('🤤', 'Drooling Face', 'Smileys & Emotion', ['drool', 'delicious']),
  e('😴', 'Sleeping Face', 'Smileys & Emotion', ['zzz', 'tired', 'sleep']),
  e('😷', 'Face with Medical Mask', 'Smileys & Emotion', ['sick', 'doctor']),
  e('🤒', 'Face with Thermometer', 'Smileys & Emotion', ['fever', 'sick']),
  e('🤕', 'Face with Head-Bandage', 'Smileys & Emotion', ['hurt', 'injured']),
  e('🤢', 'Nauseated Face', 'Smileys & Emotion', ['vomit', 'gross', 'sick']),
  e('🤮', 'Face Vomiting', 'Smileys & Emotion', ['puke', 'gross']),
  e('🤧', 'Sneezing Face', 'Smileys & Emotion', ['allergy', 'sneeze']),
  e('🥵', 'Hot Face', 'Smileys & Emotion', ['heat', 'sweat', 'summer']),
  e('🥶', 'Cold Face', 'Smileys & Emotion', ['freeze', 'ice', 'winter']),
  e('🥴', 'Woozy Face', 'Smileys & Emotion', ['drunk', 'dizzy']),
  e('😵', 'Face with Crossed-Out Eyes', 'Smileys & Emotion', ['knocked out', 'dead']),
  e('🤯', 'Exploding Head', 'Smileys & Emotion', ['mind blown', 'shock', 'boom']),
  e('🤠', 'Cowboy Hat Face', 'Smileys & Emotion', ['western', 'country']),
  e('🥳', 'Partying Face', 'Smileys & Emotion', ['celebrate', 'party', 'birthday']),
  e('🥸', 'Disguised Face', 'Smileys & Emotion', ['glasses', 'mustache', 'spy']),
  e('😎', 'Smiling Face with Sunglasses', 'Smileys & Emotion', ['cool', 'chill', 'sunglasses']),
  e('🤓', 'Nerd Face', 'Smileys & Emotion', ['geek', 'smart', 'glasses']),
  e('🧐', 'Face with Monocle', 'Smileys & Emotion', ['curious', 'inspect']),
  e('😕', 'Slightly Frowning Face', 'Smileys & Emotion', ['disappointed']),
  e('😟', 'Worried Face', 'Smileys & Emotion', ['nervous', 'anxious']),
  e('🙁', 'Frowning Face', 'Smileys & Emotion', ['sad']),
  e('😮', 'Face with Open Mouth', 'Smileys & Emotion', ['surprise', 'wow']),
  e('😯', 'Hushed Face', 'Smileys & Emotion', ['silence', 'speechless']),
  e('😲', 'Astonished Face', 'Smileys & Emotion', ['shocked', 'gasp']),
  e('😳', 'Flushed Face', 'Smileys & Emotion', ['embarrassed', 'blush']),
  e('🥺', 'Pleading Face', 'Smileys & Emotion', ['puppy eyes', 'beg', 'please']),
  e('🥹', 'Face Holding Back Tears', 'Smileys & Emotion', ['proud', 'touched', 'emotional']),
  e('😦', 'Frowning Face with Open Mouth', 'Smileys & Emotion', ['fear']),
  e('😨', 'Fearful Face', 'Smileys & Emotion', ['scared', 'dread']),
  e('😰', 'Anxious Face with Sweat', 'Smileys & Emotion', ['nervous', 'stress']),
  e('😥', 'Sad but Relieved Face', 'Smileys & Emotion', ['whew']),
  e('😢', 'Crying Face', 'Smileys & Emotion', ['tear', 'sad']),
  e('😭', 'Loudly Crying Face', 'Smileys & Emotion', ['sob', 'tears', 'crying']),
  e('😱', 'Face Screaming in Fear', 'Smileys & Emotion', ['munch', 'horror']),
  e('😖', 'Confounded Face', 'Smileys & Emotion', ['frustrated']),
  e('😣', 'Persevering Face', 'Smileys & Emotion', ['struggle']),
  e('😞', 'Disappointed Face', 'Smileys & Emotion', ['down', 'bummed']),
  e('😓', 'Downcast Face with Sweat', 'Smileys & Emotion', ['exhausted']),
  e('😩', 'Weary Face', 'Smileys & Emotion', ['tired']),
  e('😫', 'Tired Face', 'Smileys & Emotion', ['exhausted']),
  e('🥱', 'Yawning Face', 'Smileys & Emotion', ['sleepy', 'bored']),
  e('😤', 'Face with Steam From Nose', 'Smileys & Emotion', ['triumph', 'angry']),
  e('😡', 'Enraged Face', 'Smileys & Emotion', ['pout', 'mad', 'angry']),
  e('😠', 'Angry Face', 'Smileys & Emotion', ['mad', 'annoyed']),
  e('🤬', 'Face with Symbols on Mouth', 'Smileys & Emotion', ['curse', 'swear']),
  e('😈', 'Smiling Face with Horns', 'Smileys & Emotion', ['devil', 'evil']),
  e('👿', 'Angry Face with Horns', 'Smileys & Emotion', ['demon']),
  e('💀', 'Skull', 'Smileys & Emotion', ['dead', 'skeleton', 'danger']),
  e('☠️', 'Skull and Crossbones', 'Smileys & Emotion', ['pirate', 'danger', 'poison']),
  e('💩', 'Pile of Poo', 'Smileys & Emotion', ['poop', 'crap']),
  e('🤡', 'Clown Face', 'Smileys & Emotion', ['circus', 'fool']),
  e('👻', 'Ghost', 'Smileys & Emotion', ['halloween', 'spooky']),
  e('👽', 'Alien', 'Smileys & Emotion', ['ufo', 'extraterrestrial']),
  e('🤖', 'Robot', 'Smileys & Emotion', ['bot', 'ai', 'machine']),
  e('😺', 'Grinning Cat', 'Smileys & Emotion', ['cat', 'kitten', 'smile']),
  e('😸', 'Grinning Cat with Smiling Eyes', 'Smileys & Emotion', ['cat', 'laugh']),
  e('😹', 'Cat with Tears of Joy', 'Smileys & Emotion', ['cat', 'lol']),
  e('😻', 'Smiling Cat with Heart-Eyes', 'Smileys & Emotion', ['cat', 'love']),
  e('😼', 'Cat with Wry Smile', 'Smileys & Emotion', ['cat', 'smirk']),
  e('😽', 'Kissing Cat', 'Smileys & Emotion', ['cat', 'kiss']),
  e('🙀', 'Weary Cat', 'Smileys & Emotion', ['cat', 'scared']),
  e('😿', 'Crying Cat', 'Smileys & Emotion', ['cat', 'tear']),
  e('😾', 'Pouting Cat', 'Smileys & Emotion', ['cat', 'mad']),
  e('🙈', 'See-No-Evil Monkey', 'Smileys & Emotion', ['monkey', 'blind']),
  e('🙉', 'Hear-No-Evil Monkey', 'Smileys & Emotion', ['monkey', 'deaf']),
  e('🙊', 'Speak-No-Evil Monkey', 'Smileys & Emotion', ['monkey', 'mute']),
  e('💋', 'Kiss Mark', 'Smileys & Emotion', ['lipstick', 'smooch']),
  e('💌', 'Love Letter', 'Smileys & Emotion', ['heart', 'envelope', 'romance']),
  e('💘', 'Heart with Arrow', 'Smileys & Emotion', ['cupid', 'romance']),
  e('💝', 'Heart with Ribbon', 'Smileys & Emotion', ['gift', 'present']),
  e('💖', 'Sparkling Heart', 'Smileys & Emotion', ['sparkle', 'glitter', 'love']),
  e('💗', 'Growing Heart', 'Smileys & Emotion', ['pulse', 'love']),
  e('💓', 'Beating Heart', 'Smileys & Emotion', ['heartbeat']),
  e('💞', 'Revolving Hearts', 'Smileys & Emotion', ['hearts']),
  e('💕', 'Two Hearts', 'Smileys & Emotion', ['love']),
  e('💟', 'Heart Decoration', 'Smileys & Emotion', ['love']),
  e('💔', 'Broken Heart', 'Smileys & Emotion', ['breakup', 'heartbreak']),
  e('❤️', 'Red Heart', 'Smileys & Emotion', ['love', 'like']),
  e('🧡', 'Orange Heart', 'Smileys & Emotion', ['love', 'color']),
  e('💛', 'Yellow Heart', 'Smileys & Emotion', ['love', 'friendship']),
  e('💚', 'Green Heart', 'Smileys & Emotion', ['love', 'nature']),
  e('💙', 'Blue Heart', 'Smileys & Emotion', ['love', 'calm']),
  e('💜', 'Purple Heart', 'Smileys & Emotion', ['love', 'royalty']),
  e('🤎', 'Brown Heart', 'Smileys & Emotion', ['love', 'coffee']),
  e('🖤', 'Black Heart', 'Smileys & Emotion', ['love', 'dark']),
  e('🤍', 'White Heart', 'Smileys & Emotion', ['love', 'pure']),
  e('💯', 'Hundred Points', 'Smileys & Emotion', ['100', 'perfect', 'score']),
  e('💢', 'Anger Symbol', 'Smileys & Emotion', ['mad', 'anime']),
  e('💥', 'Collision', 'Smileys & Emotion', ['boom', 'explode', 'crash']),
  e('💫', 'Dizzy', 'Smileys & Emotion', ['star', 'sparkle']),
  e('💦', 'Sweat Droplets', 'Smileys & Emotion', ['water', 'splash']),
  e('💨', 'Dashing Away', 'Smileys & Emotion', ['fast', 'wind', 'run']),
  e('🕳️', 'Hole', 'Smileys & Emotion', ['void', 'black hole']),
  e('💬', 'Speech Balloon', 'Smileys & Emotion', ['chat', 'message', 'talk']),
  e('👁️‍🗨️', 'Eye in Speech Bubble', 'Smileys & Emotion', ['witness']),
  e('🗨️', 'Left Speech Bubble', 'Smileys & Emotion', ['chat']),
  e('🗯️', 'Right Anger Bubble', 'Smileys & Emotion', ['shout']),
  e('💭', 'Thought Balloon', 'Smileys & Emotion', ['think', 'dream']),
  e('💤', 'Zzz', 'Smileys & Emotion', ['sleep', 'tired']),

  // ── People & Body ──
  e('👋', 'Waving Hand', 'People & Body', ['wave', 'hello', 'bye']),
  e('🤚', 'Raised Back of Hand', 'People & Body', ['hand']),
  e('🖐️', 'Hand with Fingers Splayed', 'People & Body', ['five', 'palm']),
  e('✋', 'Raised Hand', 'People & Body', ['high five', 'stop']),
  e('🖖', 'Vulcan Salute', 'People & Body', ['spock', 'star trek']),
  e('🫱', 'Rightwards Hand', 'People & Body', ['hand']),
  e('🫲', 'Leftwards Hand', 'People & Body', ['hand']),
  e('🫳', 'Palm Down Hand', 'People & Body', ['drop']),
  e('🫴', 'Palm Up Hand', 'People & Body', ['offer']),
  e('👌', 'OK Hand', 'People & Body', ['perfect', 'okay']),
  e('🤌', 'Pinched Fingers', 'People & Body', ['italian', 'chef']),
  e('🤏', 'Pinching Hand', 'People & Body', ['small', 'tiny']),
  e('✌️', 'Victory Hand', 'People & Body', ['peace', 'two']),
  e('🤞', 'Crossed Fingers', 'People & Body', ['luck', 'hope']),
  e('🫰', 'Hand with Index Finger and Thumb Crossed', 'People & Body', ['money', 'kpop', 'love']),
  e('🤟', 'Love-You Gesture', 'People & Body', ['ily', 'love']),
  e('🤘', 'Sign of the Horns', 'People & Body', ['rock', 'metal']),
  e('🤙', 'Call Me Hand', 'People & Body', ['shaka', 'phone']),
  e('👈', 'Backhand Index Pointing Left', 'People & Body', ['point', 'left']),
  e('👉', 'Backhand Index Pointing Right', 'People & Body', ['point', 'right']),
  e('👆', 'Backhand Index Pointing Up', 'People & Body', ['point', 'up']),
  e('🖕', 'Middle Finger', 'People & Body', ['rude']),
  e('👇', 'Backhand Index Pointing Down', 'People & Body', ['point', 'down']),
  e('☝️', 'Index Pointing Up', 'People & Body', ['one', 'first']),
  e('🫵', 'Index Pointing at the Viewer', 'People & Body', ['you']),
  e('👍', 'Thumbs Up', 'People & Body', ['like', 'approve', 'yes', 'good']),
  e('👎', 'Thumbs Down', 'People & Body', ['dislike', 'no', 'bad']),
  e('✊', 'Raised Fist', 'People & Body', ['power', 'punch']),
  e('👊', 'Oncoming Fist', 'People & Body', ['brofist', 'bump']),
  e('🤛', 'Left-Facing Fist', 'People & Body', ['fist']),
  e('🤜', 'Right-Facing Fist', 'People & Body', ['fist']),
  e('👏', 'Clapping Hands', 'People & Body', ['applause', 'praise']),
  e('🙌', 'Raising Hands', 'People & Body', ['celebrate', 'hooray']),
  e('🫶', 'Heart Hands', 'People & Body', ['love', 'affection']),
  e('👐', 'Open Hands', 'People & Body', ['hands']),
  e('🤲', 'Palms Up Together', 'People & Body', ['pray', 'offer']),
  e('🤝', 'Handshake', 'People & Body', ['deal', 'agreement', 'partner']),
  e('🙏', 'Folded Hands', 'People & Body', ['pray', 'please', 'thanks', 'hope']),
  e('✍️', 'Writing Hand', 'People & Body', ['write', 'author', 'pen']),
  e('💅', 'Nail Polish', 'People & Body', ['manicure', 'sassy']),
  e('🤳', 'Selfie', 'People & Body', ['camera', 'photo']),
  e('💪', 'Flexed Biceps', 'People & Body', ['strong', 'muscle', 'gym', 'power']),
  e('🦾', 'Mechanical Arm', 'People & Body', ['robot', 'prosthetic']),
  e('🦿', 'Mechanical Leg', 'People & Body', ['robot', 'prosthetic']),
  e('🦵', 'Leg', 'People & Body', ['kick']),
  e('🦶', 'Foot', 'People & Body', ['step']),
  e('👂', 'Ear', 'People & Body', ['hear', 'listen']),
  e('🦻', 'Ear with Hearing Aid', 'People & Body', ['listen']),
  e('👃', 'Nose', 'People & Body', ['smell']),
  e('🧠', 'Brain', 'People & Body', ['smart', 'intellect', 'think', 'mind']),
  e('🫀', 'Anatomical Heart', 'People & Body', ['cardio', 'organ']),
  e('🫁', 'Lungs', 'People & Body', ['breath', 'organ']),
  e('🦷', 'Tooth', 'People & Body', ['dentist']),
  e('🦴', 'Bone', 'People & Body', ['skeleton']),
  e('👀', 'Eyes', 'People & Body', ['look', 'see', 'watch']),
  e('👁️', 'Eye', 'People & Body', ['vision', 'look']),
  e('👅', 'Tongue', 'People & Body', ['taste']),
  e('👄', 'Mouth', 'People & Body', ['lips', 'kiss']),
  e('🫦', 'Biting Lip', 'People & Body', ['nervous', 'flirt']),

  // ── Animals & Nature ──
  e('🐶', 'Dog Face', 'Animals & Nature', ['puppy', 'pet']),
  e('🐱', 'Cat Face', 'Animals & Nature', ['kitten', 'pet']),
  e('🐭', 'Mouse Face', 'Animals & Nature', ['rat']),
  e('🐹', 'Hamster', 'Animals & Nature', ['pet']),
  e('🐰', 'Rabbit Face', 'Animals & Nature', ['bunny', 'pet']),
  e('🦊', 'Fox', 'Animals & Nature', ['clever']),
  e('🐻', 'Bear', 'Animals & Nature', ['grizzly']),
  e('🐼', 'Panda', 'Animals & Nature', ['bamboo']),
  e('🐻‍❄️', 'Polar Bear', 'Animals & Nature', ['arctic', 'snow']),
  e('🐨', 'Koala', 'Animals & Nature', ['australia']),
  e('🐯', 'Tiger Face', 'Animals & Nature', ['wild']),
  e('🦁', 'Lion', 'Animals & Nature', ['king', 'safari']),
  e('🐮', 'Cow Face', 'Animals & Nature', ['milk', 'farm']),
  e('🐷', 'Pig Face', 'Animals & Nature', ['farm']),
  e('🐸', 'Frog', 'Animals & Nature', ['toad', 'amphibian']),
  e('🐵', 'Monkey Face', 'Animals & Nature', ['jungle']),
  e('🐔', 'Chicken', 'Animals & Nature', ['hen', 'farm']),
  e('🐧', 'Penguin', 'Animals & Nature', ['ice', 'bird']),
  e('🐦', 'Bird', 'Animals & Nature', ['fly', 'tweet']),
  e('🐤', 'Baby Chick', 'Animals & Nature', ['chick']),
  e('🦆', 'Duck', 'Animals & Nature', ['quack']),
  e('🦅', 'Eagle', 'Animals & Nature', ['bird', 'america']),
  e('🦉', 'Owl', 'Animals & Nature', ['wise', 'night']),
  e('🦇', 'Bat', 'Animals & Nature', ['vampire', 'night']),
  e('🐺', 'Wolf', 'Animals & Nature', ['pack', 'howl']),
  e('🐗', 'Boar', 'Animals & Nature', ['wild']),
  e('🐴', 'Horse Face', 'Animals & Nature', ['pony', 'ride']),
  e('🦄', 'Unicorn', 'Animals & Nature', ['magic', 'fantasy']),
  e('🐝', 'Honeybee', 'Animals & Nature', ['bee', 'honey']),
  e('🪱', 'Worm', 'Animals & Nature', ['earthworm']),
  e('🐛', 'Bug', 'Animals & Nature', ['insect', 'caterpillar']),
  e('🦋', 'Butterfly', 'Animals & Nature', ['caterpillar', 'pretty']),
  e('🐌', 'Snail', 'Animals & Nature', ['slow']),
  e('🐞', 'Lady Beetle', 'Animals & Nature', ['ladybug']),
  e('🐜', 'Ant', 'Animals & Nature', ['insect']),
  e('🪰', 'Fly', 'Animals & Nature', ['insect']),
  e('🪲', 'Beetle', 'Animals & Nature', ['bug']),
  e('🪳', 'Cockroach', 'Animals & Nature', ['bug']),
  e('🦟', 'Mosquito', 'Animals & Nature', ['bite', 'insect']),
  e('🦗', 'Cricket', 'Animals & Nature', ['grasshopper']),
  e('🕷️', 'Spider', 'Animals & Nature', ['web', 'arachnid']),
  e('🦂', 'Scorpion', 'Animals & Nature', ['desert']),
  e('🐢', 'Turtle', 'Animals & Nature', ['slow', 'shell']),
  e('🐍', 'Snake', 'Animals & Nature', ['python', 'reptile']),
  e('🦎', 'Lizard', 'Animals & Nature', ['gecko', 'reptile']),
  e('🦖', 'T-Rex', 'Animals & Nature', ['dinosaur', 'tyrannosaurus']),
  e('🦕', 'Sauropod', 'Animals & Nature', ['dinosaur', 'brachiosaurus']),
  e('🐙', 'Octopus', 'Animals & Nature', ['sea', 'tentacle']),
  e('🦑', 'Squid', 'Animals & Nature', ['sea', 'calamari']),
  e('🦐', 'Shrimp', 'Animals & Nature', ['seafood']),
  e('🦞', 'Lobster', 'Animals & Nature', ['seafood']),
  e('🦀', 'Crab', 'Animals & Nature', ['beach', 'seafood']),
  e('🐡', 'Blowfish', 'Animals & Nature', ['pufferfish']),
  e('🐠', 'Tropical Fish', 'Animals & Nature', ['aquarium']),
  e('🐟', 'Fish', 'Animals & Nature', ['sea']),
  e('🐬', 'Dolphin', 'Animals & Nature', ['sea', 'marine']),
  e('🐳', 'Spouting Whale', 'Animals & Nature', ['ocean']),
  e('🐋', 'Whale', 'Animals & Nature', ['ocean']),
  e('🦈', 'Shark', 'Animals & Nature', ['ocean', 'jaws']),
  e('🦭', 'Seal', 'Animals & Nature', ['sea lion']),
  e('🐊', 'Crocodile', 'Animals & Nature', ['alligator']),
  e('🐅', 'Tiger', 'Animals & Nature', ['safari']),
  e('🐆', 'Leopard', 'Animals & Nature', ['jaguar']),
  e('🦓', 'Zebra', 'Animals & Nature', ['stripes']),
  e('🦍', 'Gorilla', 'Animals & Nature', ['ape']),
  e('🦧', 'Orangutan', 'Animals & Nature', ['ape']),
  e('🐘', 'Elephant', 'Animals & Nature', ['trunk', 'safari']),
  e('🦛', 'Hippopotamus', 'Animals & Nature', ['hippo']),
  e('🦏', 'Rhinoceros', 'Animals & Nature', ['rhino']),
  e('🐪', 'Camel', 'Animals & Nature', ['desert']),
  e('🐫', 'Two-Hump Camel', 'Animals & Nature', ['desert']),
  e('🦒', 'Giraffe', 'Animals & Nature', ['tall', 'safari']),
  e('🦘', 'Kangaroo', 'Animals & Nature', ['australia', 'joey']),
  e('🦬', 'Bison', 'Animals & Nature', ['buffalo']),
  e('🐃', 'Water Buffalo', 'Animals & Nature', ['ox']),
  e('🐂', 'Ox', 'Animals & Nature', ['bull']),
  e('🐄', 'Cow', 'Animals & Nature', ['cattle']),
  e('🐎', 'Horse', 'Animals & Nature', ['gallop', 'race']),
  e('🐖', 'Pig', 'Animals & Nature', ['swine']),
  e('🐏', 'Ram', 'Animals & Nature', ['sheep', 'goat']),
  e('🐑', 'Ewe', 'Animals & Nature', ['sheep', 'wool']),
  e('🦙', 'Llama', 'Animals & Nature', ['alpaca']),
  e('🐐', 'Goat', 'Animals & Nature', ['billy']),
  e('🦌', 'Deer', 'Animals & Nature', ['buck', 'reindeer']),
  e('🐕', 'Dog', 'Animals & Nature', ['canine']),
  e('🐩', 'Poodle', 'Animals & Nature', ['dog']),
  e('🦮', 'Guide Dog', 'Animals & Nature', ['blind']),
  e('🐕‍🦺', 'Service Dog', 'Animals & Nature', ['support']),
  e('🐈', 'Cat', 'Animals & Nature', ['feline']),
  e('🐈‍⬛', 'Black Cat', 'Animals & Nature', ['halloween']),
  e('🪶', 'Feather', 'Animals & Nature', ['bird', 'light']),
  e('🐓', 'Rooster', 'Animals & Nature', ['cockerel']),
  e('🦃', 'Turkey', 'Animals & Nature', ['thanksgiving']),
  e('🦤', 'Dodo', 'Animals & Nature', ['extinct']),
  e('🦚', 'Peacock', 'Animals & Nature', ['bird', 'feathers']),
  e('🦜', 'Parrot', 'Animals & Nature', ['pirate', 'bird']),
  e('🦢', 'Swan', 'Animals & Nature', ['graceful']),
  e('🦩', 'Flamingo', 'Animals & Nature', ['pink', 'bird']),
  e('🕊️', 'Dove', 'Animals & Nature', ['peace', 'bird']),
  e('🐇', 'Rabbit', 'Animals & Nature', ['hare']),
  e('🦝', 'Raccoon', 'Animals & Nature', ['trash panda']),
  e('🦨', 'Skunk', 'Animals & Nature', ['smell']),
  e('🦡', 'Badger', 'Animals & Nature', ['honey badger']),
  e('🦫', 'Beaver', 'Animals & Nature', ['dam']),
  e('🦦', 'Otter', 'Animals & Nature', ['river']),
  e('🦥', 'Sloth', 'Animals & Nature', ['lazy', 'slow']),
  e('🐁', 'Mouse', 'Animals & Nature', ['rodent']),
  e('🐀', 'Rat', 'Animals & Nature', ['rodent']),
  e('🐿️', 'Chipmunk', 'Animals & Nature', ['squirrel']),
  e('🦔', 'Hedgehog', 'Animals & Nature', ['sonic']),
  e('🐾', 'Paw Prints', 'Animals & Nature', ['track', 'feet']),
  e('🌱', 'Seedling', 'Animals & Nature', ['plant', 'grow', 'nature']),
  e('🪴', 'Potted Plant', 'Animals & Nature', ['houseplant']),
  e('🌲', 'Evergreen Tree', 'Animals & Nature', ['pine', 'christmas']),
  e('🌳', 'Deciduous Tree', 'Animals & Nature', ['oak', 'forest']),
  e('🌴', 'Palm Tree', 'Animals & Nature', ['beach', 'summer']),
  e('🌵', 'Cactus', 'Animals & Nature', ['desert', 'spiky']),
  e('🌾', 'Sheaf of Rice', 'Animals & Nature', ['grain', 'wheat']),
  e('🌿', 'Herb', 'Animals & Nature', ['leaf', 'plant']),
  e('☘️', 'Shamrock', 'Animals & Nature', ['ireland', 'clover']),
  e('🍀', 'Four Leaf Clover', 'Animals & Nature', ['lucky', 'luck']),
  e('🍁', 'Maple Leaf', 'Animals & Nature', ['fall', 'autumn', 'canada']),
  e('🍂', 'Fallen Leaf', 'Animals & Nature', ['autumn', 'leaves']),
  e('🍃', 'Leaf Fluttering in Wind', 'Animals & Nature', ['wind', 'blow']),
  e('🪹', 'Empty Nest', 'Animals & Nature', ['bird']),
  e('🪺', 'Nest with Eggs', 'Animals & Nature', ['bird', 'eggs']),
  e('🍄', 'Mushroom', 'Animals & Nature', ['fungus', 'toadstool']),
  e('💐', 'Bouquet', 'Animals & Nature', ['flowers']),
  e('🌸', 'Cherry Blossom', 'Animals & Nature', ['flower', 'sakura']),
  e('💮', 'White Flower', 'Animals & Nature', ['flower']),
  e('🪷', 'Lotus', 'Animals & Nature', ['flower', 'zen']),
  e('🏵️', 'Rosette', 'Animals & Nature', ['flower']),
  e('🌹', 'Rose', 'Animals & Nature', ['flower', 'red', 'romance']),
  e('🥀', 'Wilted Flower', 'Animals & Nature', ['dead', 'flower']),
  e('🌺', 'Hibiscus', 'Animals & Nature', ['tropical', 'flower']),
  e('🌻', 'Sunflower', 'Animals & Nature', ['yellow', 'flower']),
  e('🌼', 'Blossom', 'Animals & Nature', ['flower', 'daisy']),
  e('🌷', 'Tulip', 'Animals & Nature', ['flower']),
  e('🪻', 'Hyacinth', 'Animals & Nature', ['flower', 'purple']),
  e('🌍', 'Globe Showing Europe-Africa', 'Animals & Nature', ['earth', 'world']),
  e('🌎', 'Globe Showing Americas', 'Animals & Nature', ['earth', 'world']),
  e('🌏', 'Globe Showing Asia-Australia', 'Animals & Nature', ['earth', 'world']),
  e('🌐', 'Globe with Meridians', 'Animals & Nature', ['internet', 'web']),
  e('🌑', 'New Moon', 'Animals & Nature', ['moon', 'dark']),
  e('🌕', 'Full Moon', 'Animals & Nature', ['moon']),
  e('🌙', 'Crescent Moon', 'Animals & Nature', ['night', 'sleep']),
  e('🌚', 'New Moon Face', 'Animals & Nature', ['moon']),
  e('🌛', 'First Quarter Moon Face', 'Animals & Nature', ['moon']),
  e('🌜', 'Last Quarter Moon Face', 'Animals & Nature', ['moon']),
  e('☀️', 'Sun', 'Animals & Nature', ['solar', 'bright', 'sunny']),
  e('🌝', 'Full Moon Face', 'Animals & Nature', ['moon']),
  e('🌞', 'Sun with Face', 'Animals & Nature', ['sun']),
  e('⭐', 'Star', 'Animals & Nature', ['favorite', 'night', 'rating']),
  e('🌟', 'Glowing Star', 'Animals & Nature', ['sparkle', 'shine']),
  e('✨', 'Sparkles', 'Animals & Nature', ['magic', 'shine', 'ai', 'clean']),
  e('⚡', 'High Voltage', 'Animals & Nature', ['lightning', 'fast', 'power', 'thunder']),
  e('☄️', 'Comet', 'Animals & Nature', ['space', 'meteor']),
  e('🔥', 'Fire', 'Animals & Nature', ['flame', 'hot', 'lit', 'burn']),
  e('🌪️', 'Tornado', 'Animals & Nature', ['twister', 'storm']),
  e('🌈', 'Rainbow', 'Animals & Nature', ['pride', 'colors']),
  e('☁️', 'Cloud', 'Animals & Nature', ['weather', 'sky']),
  e('🌧️', 'Cloud with Rain', 'Animals & Nature', ['rain', 'weather']),
  e('⛈️', 'Cloud with Lightning and Rain', 'Animals & Nature', ['storm']),
  e('🌩️', 'Cloud with Lightning', 'Animals & Nature', ['thunder']),
  e('🌨️', 'Cloud with Snow', 'Animals & Nature', ['snow', 'cold']),
  e('❄️', 'Snowflake', 'Animals & Nature', ['winter', 'cold', 'ice']),
  e('☃️', 'Snowman', 'Animals & Nature', ['winter']),
  e('⛄', 'Snowman Without Snow', 'Animals & Nature', ['winter']),
  e('💨', 'Dashing Away', 'Animals & Nature', ['wind']),
  e('💧', 'Droplet', 'Animals & Nature', ['water', 'rain']),
  e('🌊', 'Water Wave', 'Animals & Nature', ['ocean', 'sea', 'tsunami']),

  // ── Food & Drink ──
  e('🍏', 'Green Apple', 'Food & Drink', ['fruit']),
  e('🍎', 'Red Apple', 'Food & Drink', ['fruit']),
  e('🍐', 'Pear', 'Food & Drink', ['fruit']),
  e('🍊', 'Tangerine', 'Food & Drink', ['orange', 'citrus']),
  e('🍋', 'Lemon', 'Food & Drink', ['sour', 'citrus']),
  e('🍌', 'Banana', 'Food & Drink', ['fruit']),
  e('🍉', 'Watermelon', 'Food & Drink', ['summer', 'fruit']),
  e('🍇', 'Grapes', 'Food & Drink', ['wine', 'fruit']),
  e('🍓', 'Strawberry', 'Food & Drink', ['berry', 'fruit']),
  e('🫐', 'Blueberries', 'Food & Drink', ['berry']),
  e('🍈', 'Melon', 'Food & Drink', ['fruit']),
  e('🍒', 'Cherries', 'Food & Drink', ['fruit']),
  e('🍑', 'Peach', 'Food & Drink', ['fruit']),
  e('🥭', 'Mango', 'Food & Drink', ['tropical', 'fruit']),
  e('🍍', 'Pineapple', 'Food & Drink', ['tropical', 'fruit']),
  e('🥥', 'Coconut', 'Food & Drink', ['tropical']),
  e('🥝', 'Kiwi Fruit', 'Food & Drink', ['fruit']),
  e('🍅', 'Tomato', 'Food & Drink', ['vegetable']),
  e('🥑', 'Avocado', 'Food & Drink', ['guacamole']),
  e('🍆', 'Eggplant', 'Food & Drink', ['aubergine']),
  e('🥔', 'Potato', 'Food & Drink', ['spud']),
  e('🥕', 'Carrot', 'Food & Drink', ['vegetable']),
  e('🌽', 'Ear of Corn', 'Food & Drink', ['maize']),
  e('🌶️', 'Hot Pepper', 'Food & Drink', ['spicy', 'chili']),
  e('🫑', 'Bell Pepper', 'Food & Drink', ['capsicum']),
  e('🥒', 'Cucumber', 'Food & Drink', ['pickle']),
  e('🥬', 'Leafy Green', 'Food & Drink', ['salad', 'lettuce']),
  e('🥦', 'Broccoli', 'Food & Drink', ['vegetable']),
  e('🧄', 'Garlic', 'Food & Drink', ['cooking']),
  e('🧅', 'Onion', 'Food & Drink', ['cooking']),
  e('🥜', 'Peanuts', 'Food & Drink', ['nuts']),
  e('🫘', 'Beans', 'Food & Drink', ['legume']),
  e('🌰', 'Chestnut', 'Food & Drink', ['nut']),
  e('🍞', 'Bread', 'Food & Drink', ['toast', 'bakery']),
  e('🥐', 'Croissant', 'Food & Drink', ['pastry', 'french']),
  e('🥖', 'Baguette Bread', 'Food & Drink', ['french', 'bread']),
  e('🫓', 'Flatbread', 'Food & Drink', ['pita', 'naan']),
  e('🥨', 'Pretzel', 'Food & Drink', ['snack']),
  e('🥯', 'Bagel', 'Food & Drink', ['bakery']),
  e('🥞', 'Pancakes', 'Food & Drink', ['breakfast', 'syrup']),
  e('🧇', 'Waffle', 'Food & Drink', ['breakfast']),
  e('🧀', 'Cheese Wedge', 'Food & Drink', ['cheddar', 'dairy']),
  e('🍖', 'Meat on Bone', 'Food & Drink', ['meat', 'bbq']),
  e('🍗', 'Poultry Leg', 'Food & Drink', ['chicken', 'drumstick']),
  e('🥩', 'Cut of Meat', 'Food & Drink', ['steak', 'beef']),
  e('🥓', 'Bacon', 'Food & Drink', ['breakfast', 'pork']),
  e('🍔', 'Hamburger', 'Food & Drink', ['burger', 'fast food']),
  e('🍟', 'French Fries', 'Food & Drink', ['chips', 'fast food']),
  e('🍕', 'Pizza', 'Food & Drink', ['slice', 'cheese']),
  e('🌭', 'Hot Dog', 'Food & Drink', ['sausage', 'fast food']),
  e('🥪', 'Sandwich', 'Food & Drink', ['lunch']),
  e('🌮', 'Taco', 'Food & Drink', ['mexican']),
  e('🌯', 'Burrito', 'Food & Drink', ['mexican']),
  e('🫔', 'Tamale', 'Food & Drink', ['mexican']),
  e('🥙', 'Stuffed Flatbread', 'Food & Drink', ['pita', 'gyro', 'kebab']),
  e('🧆', 'Falafel', 'Food & Drink', ['middle eastern']),
  e('🥚', 'Egg', 'Food & Drink', ['breakfast']),
  e('🍳', 'Cooking', 'Food & Drink', ['fried egg', 'pan']),
  e('🥘', 'Shallow Pan of Food', 'Food & Drink', ['paella']),
  e('🍲', 'Pot of Food', 'Food & Drink', ['soup', 'stew']),
  e('🫕', 'Fondue', 'Food & Drink', ['cheese']),
  e('🥣', 'Bowl with Spoon', 'Food & Drink', ['cereal', 'soup']),
  e('🥗', 'Green Salad', 'Food & Drink', ['healthy']),
  e('🍿', 'Popcorn', 'Food & Drink', ['movie', 'snack']),
  e('🧈', 'Butter', 'Food & Drink', ['dairy']),
  e('🧂', 'Salt', 'Food & Drink', ['seasoning']),
  e('🥫', 'Canned Food', 'Food & Drink', ['tin', 'can']),
  e('🍱', 'Bento Box', 'Food & Drink', ['japanese', 'lunch']),
  e('🍘', 'Rice Cracker', 'Food & Drink', ['senbei']),
  e('🍙', 'Rice Ball', 'Food & Drink', ['onigiri']),
  e('🍚', 'Cooked Rice', 'Food & Drink', ['bowl']),
  e('🍛', 'Curry Rice', 'Food & Drink', ['spicy']),
  e('🍜', 'Steaming Bowl', 'Food & Drink', ['ramen', 'noodles']),
  e('🍝', 'Spaghetti', 'Food & Drink', ['pasta', 'italian']),
  e('🍠', 'Roasted Sweet Potato', 'Food & Drink', ['yam']),
  e('🍢', 'Oden', 'Food & Drink', ['japanese']),
  e('🍣', 'Sushi', 'Food & Drink', ['japanese', 'fish']),
  e('🍤', 'Fried Shrimp', 'Food & Drink', ['tempura']),
  e('🍥', 'Fish Cake with Swirl', 'Food & Drink', ['naruto']),
  e('🥮', 'Moon Cake', 'Food & Drink', ['festival']),
  e('🍡', 'Dango', 'Food & Drink', ['japanese', 'dessert']),
  e('🥟', 'Dumpling', 'Food & Drink', ['gyoza', 'dim sum']),
  e('🥠', 'Fortune Cookie', 'Food & Drink', ['chinese']),
  e('🥡', 'Takeout Box', 'Food & Drink', ['chinese food']),
  e('🍦', 'Soft Ice Cream', 'Food & Drink', ['dessert']),
  e('🍧', 'Shaved Ice', 'Food & Drink', ['dessert']),
  e('🍨', 'Ice Cream', 'Food & Drink', ['dessert', 'sundae']),
  e('🍩', 'Doughnut', 'Food & Drink', ['donut', 'dessert']),
  e('🍪', 'Cookie', 'Food & Drink', ['biscuit', 'chocolate chip']),
  e('🎂', 'Birthday Cake', 'Food & Drink', ['party', 'cake']),
  e('🍰', 'Shortcake', 'Food & Drink', ['cake', 'slice']),
  e('🧁', 'Cupcake', 'Food & Drink', ['bakery', 'dessert']),
  e('🥧', 'Pie', 'Food & Drink', ['pastry', 'dessert']),
  e('🍫', 'Chocolate Bar', 'Food & Drink', ['candy', 'sweet']),
  e('🍬', 'Candy', 'Food & Drink', ['sweet']),
  e('🍭', 'Lollipop', 'Food & Drink', ['candy']),
  e('🍮', 'Custard', 'Food & Drink', ['pudding', 'flan']),
  e('🍯', 'Honey Pot', 'Food & Drink', ['sweet', 'honey']),
  e('🍼', 'Baby Bottle', 'Food & Drink', ['milk']),
  e('🥛', 'Glass of Milk', 'Food & Drink', ['dairy']),
  e('☕', 'Hot Beverage', 'Food & Drink', ['coffee', 'tea', 'cafe']),
  e('🫖', 'Teapot', 'Food & Drink', ['tea']),
  e('🍵', 'Teacup Without Handle', 'Food & Drink', ['green tea', 'matcha']),
  e('🍶', 'Sake', 'Food & Drink', ['japanese', 'alcohol']),
  e('🍾', 'Bottle with Popping Cork', 'Food & Drink', ['champagne', 'celebrate']),
  e('🍷', 'Wine Glass', 'Food & Drink', ['alcohol', 'red wine']),
  e('🍸', 'Cocktail Glass', 'Food & Drink', ['martini', 'drink']),
  e('🍹', 'Tropical Drink', 'Food & Drink', ['cocktail']),
  e('🍺', 'Beer Mug', 'Food & Drink', ['alcohol', 'brew']),
  e('🍻', 'Clinking Beer Mugs', 'Food & Drink', ['cheers', 'toast']),
  e('🥂', 'Clinking Glasses', 'Food & Drink', ['cheers', 'celebrate']),
  e('🥃', 'Tumbler Glass', 'Food & Drink', ['whiskey']),
  e('🥤', 'Cup with Straw', 'Food & Drink', ['soda']),
  e('🧋', 'Bubble Tea', 'Food & Drink', ['boba', 'milk tea']),
  e('🧃', 'Beverage Box', 'Food & Drink', ['juice']),
  e('🧉', 'Mate', 'Food & Drink', ['tea']),
  e('🧊', 'Ice', 'Food & Drink', ['cold', 'cube']),
  e('🥢', 'Chopsticks', 'Food & Drink', ['asian', 'cutlery']),
  e('🍽️', 'Fork and Knife with Plate', 'Food & Drink', ['dinner', 'dining']),
  e('🍴', 'Fork and Knife', 'Food & Drink', ['cutlery', 'restaurant']),
  e('🥄', 'Spoon', 'Food & Drink', ['cutlery']),
  e('🔪', 'Kitchen Knife', 'Food & Drink', ['chef', 'cook']),
  e('🫗', 'Pouring Liquid', 'Food & Drink', ['spill']),
  e('🏺', 'Amphora', 'Food & Drink', ['vase', 'ancient']),

  // ── Activities ──
  e('⚽', 'Soccer Ball', 'Activities', ['football', 'sport']),
  e('🏀', 'Basketball', 'Activities', ['sport', 'nba']),
  e('🏈', 'American Football', 'Activities', ['nfl', 'sport']),
  e('⚾', 'Baseball', 'Activities', ['sport', 'mlb']),
  e('🥎', 'Softball', 'Activities', ['sport']),
  e('🎾', 'Tennis', 'Activities', ['sport', 'racket']),
  e('🏐', 'Volleyball', 'Activities', ['sport']),
  e('🏉', 'Rugby Football', 'Activities', ['sport']),
  e('🥏', 'Flying Disc', 'Activities', ['frisbee']),
  e('🎱', 'Pool 8 Ball', 'Activities', ['billiards']),
  e('🪀', 'Yo-Yo', 'Activities', ['toy']),
  e('🏓', 'Ping Pong', 'Activities', ['table tennis']),
  e('🏸', 'Badminton', 'Activities', ['sport']),
  e('🏒', 'Ice Hockey', 'Activities', ['sport']),
  e('🏑', 'Field Hockey', 'Activities', ['sport']),
  e('🥍', 'Lacrosse', 'Activities', ['sport']),
  e('🏏', 'Cricket Game', 'Activities', ['sport']),
  e('🪃', 'Boomerang', 'Activities', ['australia']),
  e('🥅', 'Goal Net', 'Activities', ['sport', 'soccer']),
  e('⛳', 'Flag in Hole', 'Activities', ['golf']),
  e('🪁', 'Kite', 'Activities', ['fly']),
  e('🛝', 'Playground Slide', 'Activities', ['park']),
  e('🏹', 'Bow and Arrow', 'Activities', ['archery']),
  e('🎣', 'Fishing Pole', 'Activities', ['fish', 'catch']),
  e('🤿', 'Diving Mask', 'Activities', ['scuba', 'snorkel']),
  e('🥊', 'Boxing Glove', 'Activities', ['fight', 'sport']),
  e('🥋', 'Martial Arts Uniform', 'Activities', ['karate', 'judo']),
  e('🎽', 'Running Shirt', 'Activities', ['marathon']),
  e('🛹', 'Skateboard', 'Activities', ['skate', 'board']),
  e('🛼', 'Roller Skate', 'Activities', ['skate']),
  e('🛷', 'Sled', 'Activities', ['sledge']),
  e('⛸️', 'Ice Skate', 'Activities', ['skate']),
  e('🥌', 'Curling Stone', 'Activities', ['sport']),
  e('🎿', 'Skis', 'Activities', ['snow', 'skiing']),
  e('⛷️', 'Skier', 'Activities', ['snow']),
  e('🏂', 'Snowboarder', 'Activities', ['snow', 'board']),
  e('🪂', 'Parachute', 'Activities', ['skydive']),
  e('🏋️', 'Person Lifting Weights', 'Activities', ['gym', 'workout', 'fitness']),
  e('🤼', 'People Wrestling', 'Activities', ['wrestling']),
  e('🤸', 'Person Cartwheeling', 'Activities', ['gymnastics']),
  e('⛹️', 'Person Bouncing Ball', 'Activities', ['basketball']),
  e('🤺', 'Person Fencing', 'Activities', ['sword']),
  e('🤾', 'Person Playing Handball', 'Activities', ['handball']),
  e('🏌️', 'Person Golfing', 'Activities', ['golf']),
  e('🏇', 'Horse Racing', 'Activities', ['jockey']),
  e('🧘', 'Person in Lotus Position', 'Activities', ['yoga', 'meditate', 'zen']),
  e('🏄', 'Person Surfing', 'Activities', ['surf', 'wave']),
  e('🏊', 'Person Swimming', 'Activities', ['swim', 'pool']),
  e('🤽', 'Person Playing Water Polo', 'Activities', ['water polo']),
  e('🚣', 'Person Rowing Boat', 'Activities', ['row']),
  e('🧗', 'Person Climbing', 'Activities', ['climb', 'rock']),
  e('🚵', 'Person Mountain Biking', 'Activities', ['bike']),
  e('🚴', 'Person Biking', 'Activities', ['bicycle', 'cycling']),
  e('🏆', 'Trophy', 'Activities', ['winner', 'first', 'award', 'gold']),
  e('🥇', '1st Place Medal', 'Activities', ['gold', 'winner']),
  e('🥈', '2nd Place Medal', 'Activities', ['silver']),
  e('🥉', '3rd Place Medal', 'Activities', ['bronze']),
  e('🏅', 'Sports Medal', 'Activities', ['award']),
  e('🎖️', 'Military Medal', 'Activities', ['honor']),
  e('🏵️', 'Rosette', 'Activities', ['award']),
  e('🎗️', 'Reminder Ribbon', 'Activities', ['awareness']),
  e('🎫', 'Ticket', 'Activities', ['entry', 'pass']),
  e('🎟️', 'Admission Tickets', 'Activities', ['movie', 'concert']),
  e('🎪', 'Circus Tent', 'Activities', ['carnival']),
  e('🤹', 'Person Juggling', 'Activities', ['circus']),
  e('🎭', 'Performing Arts', 'Activities', ['theater', 'drama', 'mask']),
  e('🩰', 'Ballet Shoes', 'Activities', ['dance']),
  e('🎨', 'Artist Palette', 'Activities', ['art', 'paint', 'design', 'creative']),
  e('🎬', 'Clapper Board', 'Activities', ['movie', 'film', 'cinema']),
  e('🎤', 'Microphone', 'Activities', ['sing', 'karaoke', 'voice', 'audio']),
  e('🎧', 'Headphone', 'Activities', ['music', 'listen', 'audio']),
  e('🎼', 'Musical Score', 'Activities', ['music']),
  e('🎹', 'Musical Keyboard', 'Activities', ['piano']),
  e('🥁', 'Drum', 'Activities', ['percussion']),
  e('🪘', 'Long Drum', 'Activities', ['bongo']),
  e('🎷', 'Saxophone', 'Activities', ['jazz', 'music']),
  e('🎺', 'Trumpet', 'Activities', ['brass', 'music']),
  e('🎸', 'Guitar', 'Activities', ['rock', 'instrument']),
  e('🪕', 'Banjo', 'Activities', ['music']),
  e('🎻', 'Violin', 'Activities', ['classical', 'strings']),
  e('🎲', 'Game Die', 'Activities', ['dice', 'board game', 'random']),
  e('♟️', 'Chess Pawn', 'Activities', ['chess', 'strategy']),
  e('🎯', 'Bullseye', 'Activities', ['target', 'dart', 'goal', 'hit']),
  e('🎳', 'Bowling', 'Activities', ['pins']),
  e('🎮', 'Video Game', 'Activities', ['controller', 'gaming', 'play']),
  e('🎰', 'Slot Machine', 'Activities', ['casino', 'gamble']),
  e('🧩', 'Puzzle Piece', 'Activities', ['jigsaw', 'problem', 'solve']),

  // ── Travel & Places ──
  e('🚗', 'Automobile', 'Travel & Places', ['car', 'drive']),
  e('🚕', 'Taxi', 'Travel & Places', ['cab']),
  e('🚙', 'Sport Utility Vehicle', 'Travel & Places', ['suv']),
  e('🚌', 'Bus', 'Travel & Places', ['transit']),
  e('🚎', 'Trolleybus', 'Travel & Places', ['transit']),
  e('🏎️', 'Racing Car', 'Travel & Places', ['f1', 'fast']),
  e('🚓', 'Police Car', 'Travel & Places', ['cop']),
  e('🚑', 'Ambulance', 'Travel & Places', ['hospital', 'emergency']),
  e('🚒', 'Fire Engine', 'Travel & Places', ['fire truck']),
  e('🚐', 'Minibus', 'Travel & Places', ['van']),
  e('🛻', 'Pickup Truck', 'Travel & Places', ['truck']),
  e('🚚', 'Delivery Truck', 'Travel & Places', ['package', 'cargo']),
  e('🚛', 'Articulated Lorry', 'Travel & Places', ['semi']),
  e('🚜', 'Tractor', 'Travel & Places', ['farm']),
  e('🦯', 'White Cane', 'Travel & Places', ['blind']),
  e('🦽', 'Manual Wheelchair', 'Travel & Places', ['disability']),
  e('🦼', 'Motorized Wheelchair', 'Travel & Places', ['disability']),
  e('🛴', 'Kick Scooter', 'Travel & Places', ['scooter']),
  e('🚲', 'Bicycle', 'Travel & Places', ['bike']),
  e('🛵', 'Motor Scooter', 'Travel & Places', ['moped', 'vespa']),
  e('🏍️', 'Motorcycle', 'Travel & Places', ['motorbike']),
  e('🛺', 'Auto Rickshaw', 'Travel & Places', ['tuk tuk']),
  e('🚨', 'Police Car Light', 'Travel & Places', ['siren', 'alert', 'emergency']),
  e('🚔', 'Oncoming Police Car', 'Travel & Places', ['police']),
  e('🚍', 'Oncoming Bus', 'Travel & Places', ['transit']),
  e('🚘', 'Oncoming Automobile', 'Travel & Places', ['car']),
  e('🚖', 'Oncoming Taxi', 'Travel & Places', ['cab']),
  e('🚡', 'Aerial Tramway', 'Travel & Places', ['cable car']),
  e('🚠', 'Mountain Cableway', 'Travel & Places', ['gondola']),
  e('🚟', 'Suspension Railway', 'Travel & Places', ['train']),
  e('🚃', 'Railway Car', 'Travel & Places', ['train']),
  e('🚋', 'Tram Car', 'Travel & Places', ['streetcar']),
  e('🚞', 'Mountain Railway', 'Travel & Places', ['train']),
  e('🚝', 'Monorail', 'Travel & Places', ['train']),
  e('🚄', 'High-Speed Train', 'Travel & Places', ['shinkansen', 'bullet train']),
  e('🚅', 'Bullet Train', 'Travel & Places', ['fast', 'shinkansen']),
  e('🚈', 'Light Rail', 'Travel & Places', ['train']),
  e('🚂', 'Locomotive', 'Travel & Places', ['steam train']),
  e('🚆', 'Train', 'Travel & Places', ['railway']),
  e('🚇', 'Metro', 'Travel & Places', ['subway']),
  e('🚊', 'Tram', 'Travel & Places', ['trolley']),
  e('🚉', 'Station', 'Travel & Places', ['train station']),
  e('✈️', 'Airplane', 'Travel & Places', ['flight', 'plane', 'travel']),
  e('🛫', 'Airplane Departure', 'Travel & Places', ['takeoff']),
  e('🛬', 'Airplane Arrival', 'Travel & Places', ['landing']),
  e('🛩️', 'Small Airplane', 'Travel & Places', ['flight']),
  e('💺', 'Seat', 'Travel & Places', ['chair', 'flight']),
  e('🛰️', 'Satellite', 'Travel & Places', ['space', 'orbit']),
  e('🚀', 'Rocket', 'Travel & Places', ['space', 'launch', 'startup', 'fast']),
  e('🛸', 'Flying Saucer', 'Travel & Places', ['ufo', 'alien']),
  e('🚁', 'Helicopter', 'Travel & Places', ['chopper']),
  e('🛶', 'Canoe', 'Travel & Places', ['boat', 'kayak']),
  e('⛵', 'Sailboat', 'Travel & Places', ['boat', 'sea']),
  e('🚤', 'Speedboat', 'Travel & Places', ['boat']),
  e('🛥️', 'Motor Boat', 'Travel & Places', ['yacht']),
  e('🛳️', 'Passenger Ship', 'Travel & Places', ['cruise']),
  e('⛴️', 'Ferry', 'Travel & Places', ['boat']),
  e('🚢', 'Ship', 'Travel & Places', ['boat', 'cargo']),
  e('⚓', 'Anchor', 'Travel & Places', ['ship', 'nautical', 'harbor']),
  e('🛟', 'Ring Buoy', 'Travel & Places', ['lifesaver']),
  e('⛽', 'Fuel Pump', 'Travel & Places', ['gas', 'petrol']),
  e('🚧', 'Construction', 'Travel & Places', ['barrier', 'wip']),
  e('🚦', 'Vertical Traffic Light', 'Travel & Places', ['signal']),
  e('🚥', 'Horizontal Traffic Light', 'Travel & Places', ['signal']),
  e('🚏', 'Bus Stop', 'Travel & Places', ['transit']),
  e('🗺️', 'World Map', 'Travel & Places', ['travel', 'geography', 'location']),
  e('🗿', 'Moai', 'Travel & Places', ['easter island', 'stone']),
  e('🗽', 'Statue of Liberty', 'Travel & Places', ['new york', 'usa']),
  e('🗼', 'Tokyo Tower', 'Travel & Places', ['japan']),
  e('🏰', 'Castle', 'Travel & Places', ['fairytale', 'disney']),
  e('🏯', 'Japanese Castle', 'Travel & Places', ['japan']),
  e('🏟️', 'Stadium', 'Travel & Places', ['arena', 'sports']),
  e('🎡', 'Ferris Wheel', 'Travel & Places', ['amusement park']),
  e('🎢', 'Roller Coaster', 'Travel & Places', ['theme park']),
  e('🎠', 'Carousel Horse', 'Travel & Places', ['carnival']),
  e('⛲', 'Fountain', 'Travel & Places', ['park']),
  e('⛱️', 'Umbrella on Ground', 'Travel & Places', ['beach', 'summer']),
  e('🏖️', 'Beach with Umbrella', 'Travel & Places', ['vacation', 'sea']),
  e('🏝️', 'Desert Island', 'Travel & Places', ['tropical']),
  e('🏜️', 'Desert', 'Travel & Places', ['sahara', 'sand']),
  e('🌋', 'Volcano', 'Travel & Places', ['lava', 'eruption']),
  e('⛰️', 'Mountain', 'Travel & Places', ['nature', 'peak', 'hike']),
  e('🏔️', 'Snow-Capped Mountain', 'Travel & Places', ['alps', 'everest']),
  e('🏕️', 'Camping', 'Travel & Places', ['tent', 'outdoors']),
  e('⛺', 'Tent', 'Travel & Places', ['camp']),
  e('🏠', 'House', 'Travel & Places', ['home']),
  e('🏡', 'House with Garden', 'Travel & Places', ['home']),
  e('🏢', 'Office Building', 'Travel & Places', ['work', 'company']),
  e('🏣', 'Japanese Post Office', 'Travel & Places', ['mail']),
  e('🏤', 'Post Office', 'Travel & Places', ['mail']),
  e('🏥', 'Hospital', 'Travel & Places', ['clinic', 'doctor']),
  e('🏦', 'Bank', 'Travel & Places', ['money']),
  e('🏨', 'Hotel', 'Travel & Places', ['lodging', 'travel']),
  e('🏩', 'Love Hotel', 'Travel & Places', ['hotel']),
  e('🏪', 'Convenience Store', 'Travel & Places', ['7-eleven', 'shop']),
  e('🏫', 'School', 'Travel & Places', ['education', 'study']),
  e('🏬', 'Department Store', 'Travel & Places', ['mall', 'shopping']),
  e('🏭', 'Factory', 'Travel & Places', ['industry']),
  e('🏛️', 'Classical Building', 'Travel & Places', ['museum', 'capitol', 'greek']),
  e('⛪', 'Church', 'Travel & Places', ['religion']),
  e('🕌', 'Mosque', 'Travel & Places', ['islam']),
  e('🛕', 'Hindu Temple', 'Travel & Places', ['hindu']),
  e('🕍', 'Synagogue', 'Travel & Places', ['jewish']),
  e('⛩️', 'Shinto Shrine', 'Travel & Places', ['torii', 'japan']),
  e('🕋', 'Kaaba', 'Travel & Places', ['mecca']),
  e('🛤️', 'Railway Track', 'Travel & Places', ['train']),
  e('🛣️', 'Motorway', 'Travel & Places', ['highway']),
  e('🗾', 'Map of Japan', 'Travel & Places', ['japan']),
  e('🎑', 'Moon Viewing Ceremony', 'Travel & Places', ['tsukimi']),
  e('🌅', 'Sunrise', 'Travel & Places', ['morning']),
  e('🌄', 'Sunrise Over Mountains', 'Travel & Places', ['morning']),
  e('🌠', 'Shooting Star', 'Travel & Places', ['wish', 'space']),
  e('🎇', 'Sparkler', 'Travel & Places', ['firework', 'celebrate']),
  e('🎆', 'Fireworks', 'Travel & Places', ['celebrate', 'new year']),
  e('🌇', 'Sunset', 'Travel & Places', ['evening']),
  e('🌆', 'Cityscape at Dusk', 'Travel & Places', ['skyline']),
  e('🏙️', 'Cityscape', 'Travel & Places', ['buildings', 'skyline']),
  e('🌃', 'Night with Stars', 'Travel & Places', ['city', 'night']),
  e('🌌', 'Milky Way', 'Travel & Places', ['space', 'galaxy']),
  e('🌉', 'Bridge at Night', 'Travel & Places', ['san francisco']),
  e('🌁', 'Foggy', 'Travel & Places', ['fog']),

  // ── Objects ──
  e('💡', 'Light Bulb', 'Objects', ['idea', 'bright', 'innovation']),
  e('🔦', 'Flashlight', 'Objects', ['torch']),
  e('🏮', 'Red Paper Lantern', 'Objects', ['izakaya', 'japan']),
  e('🪔', 'Diya Lamp', 'Objects', ['oil lamp', 'diwali']),
  e('🧱', 'Brick', 'Objects', ['build', 'wall']),
  e('🪵', 'Wood', 'Objects', ['log', 'timber']),
  e('🪨', 'Rock', 'Objects', ['stone', 'boulder']),
  e('🪰', 'Fly', 'Objects', ['bug']),
  e('🧰', 'Toolbox', 'Objects', ['tools', 'repair', 'kit']),
  e('🔧', 'Wrench', 'Objects', ['fix', 'tool', 'spanner']),
  e('🪛', 'Screwdriver', 'Objects', ['tool']),
  e('🔩', 'Nut and Bolt', 'Objects', ['screw', 'hardware']),
  e('⚙️', 'Gear', 'Objects', ['settings', 'config', 'cog', 'preferences']),
  e('🗜️', 'Clamp', 'Objects', ['vice']),
  e('🪜', 'Ladder', 'Objects', ['climb']),
  e('🔨', 'Hammer', 'Objects', ['tool', 'build']),
  e('⚒️', 'Hammer and Pick', 'Objects', ['mining', 'tools']),
  e('🛠️', 'Hammer and Wrench', 'Objects', ['tools', 'build', 'fix']),
  e('⛏️', 'Pick', 'Objects', ['mining']),
  e('🪓', 'Axe', 'Objects', ['wood', 'chop']),
  e('🪚', 'Carpentry Saw', 'Objects', ['cut', 'wood']),
  e('🗡️', 'Dagger', 'Objects', ['knife', 'weapon']),
  e('⚔️', 'Crossed Swords', 'Objects', ['battle', 'fight']),
  e('💣', 'Bomb', 'Objects', ['explosive', 'boom']),
  e('🪃', 'Boomerang', 'Objects', ['weapon']),
  e('🛡️', 'Shield', 'Objects', ['protect', 'defense', 'security']),
  e('🔮', 'Crystal Ball', 'Objects', ['fortune', 'magic']),
  e('🪄', 'Magic Wand', 'Objects', ['magic', 'spell', 'ai']),
  e('🧿', 'Nazar Amulet', 'Objects', ['evil eye']),
  e('🪬', 'Hamsa', 'Objects', ['amulet', 'protection']),
  e('💈', 'Barber Pole', 'Objects', ['haircut']),
  e('🧲', 'Magnet', 'Objects', ['attract', 'physics']),
  e('⚗️', 'Alembic', 'Objects', ['chemistry', 'lab']),
  e('🧪', 'Test Tube', 'Objects', ['science', 'experiment', 'chemistry']),
  e('🧫', 'Petri Dish', 'Objects', ['biology', 'lab']),
  e('🧬', 'DNA', 'Objects', ['genetics', 'science']),
  e('🔬', 'Microscope', 'Objects', ['science', 'lab', 'research']),
  e('🔭', 'Telescope', 'Objects', ['astronomy', 'stars']),
  e('📡', 'Satellite Antenna', 'Objects', ['dish', 'comm']),
  e('💉', 'Syringe', 'Objects', ['vaccine', 'shot', 'medical']),
  e('🩸', 'Drop of Blood', 'Objects', ['bleed']),
  e('💊', 'Pill', 'Objects', ['medicine', 'drug']),
  e('🩹', 'Adhesive Bandage', 'Objects', ['bandaid']),
  e('🩺', 'Stethoscope', 'Objects', ['doctor', 'heart']),
  e('🩻', 'X-Ray', 'Objects', ['bone']),
  e('🚪', 'Door', 'Objects', ['enter', 'exit']),
  e('🪟', 'Window', 'Objects', ['glass']),
  e('🪞', 'Mirror', 'Objects', ['reflection']),
  e('🪑', 'Chair', 'Objects', ['seat']),
  e('🛋️', 'Couch and Lamp', 'Objects', ['sofa', 'living room']),
  e('🛏️', 'Bed', 'Objects', ['sleep', 'hotel']),
  e('🛁', 'Bathtub', 'Objects', ['bath']),
  e('🚿', 'Shower', 'Objects', ['water']),
  e('🚽', 'Toilet', 'Objects', ['bathroom']),
  e('🧻', 'Roll of Paper', 'Objects', ['toilet paper']),
  e('🧹', 'Broom', 'Objects', ['clean', 'sweep']),
  e('🧺', 'Basket', 'Objects', ['laundry']),
  e('🧽', 'Sponge', 'Objects', ['cleaning']),
  e('🪣', 'Bucket', 'Objects', ['pail']),
  e('🧼', 'Soap', 'Objects', ['wash', 'clean']),
  e('🫧', 'Bubbles', 'Objects', ['soap', 'water']),
  e('🪥', 'Toothbrush', 'Objects', ['teeth']),
  e('🔑', 'Key', 'Objects', ['lock', 'password', 'access']),
  e('🗝️', 'Old Key', 'Objects', ['vintage', 'secret']),
  e('🔒', 'Locked', 'Objects', ['security', 'protect', 'private']),
  e('🔓', 'Unlocked', 'Objects', ['open', 'access']),
  e('🔏', 'Locked with Pen', 'Objects', ['privacy']),
  e('🔐', 'Locked with Key', 'Objects', ['security']),
  e('🔔', 'Bell', 'Objects', ['notification', 'alert', 'alarm']),
  e('🔕', 'Bell with Slash', 'Objects', ['mute', 'silent']),
  e('📦', 'Package', 'Objects', ['box', 'delivery', 'parcel']),
  e('📫', 'Closed Mailbox with Raised Flag', 'Objects', ['mail']),
  e('📬', 'Open Mailbox with Raised Flag', 'Objects', ['mail']),
  e('📭', 'Open Mailbox with Lowered Flag', 'Objects', ['mail']),
  e('📮', 'Postbox', 'Objects', ['mail']),
  e('📯', 'Postal Horn', 'Objects', ['horn']),
  e('📜', 'Scroll', 'Objects', ['parchment', 'history', 'paper']),
  e('📃', 'Page with Curl', 'Objects', ['document']),
  e('📄', 'Page Facing Up', 'Objects', ['file', 'doc', 'document']),
  e('📑', 'Bookmark Tabs', 'Objects', ['organize']),
  e('🧾', 'Receipt', 'Objects', ['bill', 'expense']),
  e('📊', 'Bar Chart', 'Objects', ['analytics', 'data', 'graph', 'metrics']),
  e('📈', 'Chart Increasing', 'Objects', ['growth', 'stocks', 'success']),
  e('📉', 'Chart Decreasing', 'Objects', ['loss', 'drop']),
  e('🗒️', 'Spiral Notepad', 'Objects', ['notes', 'memo']),
  e('🗓️', 'Spiral Calendar', 'Objects', ['schedule', 'date']),
  e('📆', 'Tear-Off Calendar', 'Objects', ['date']),
  e('📅', 'Calendar', 'Objects', ['date', 'schedule', 'planner', 'event']),
  e('🗑️', 'Wastebasket', 'Objects', ['trash', 'bin', 'delete']),
  e('🪪', 'Identification Card', 'Objects', ['id', 'license']),
  e('🗂️', 'Card Index Dividers', 'Objects', ['organize']),
  e('🗃️', 'Card File Box', 'Objects', ['archive']),
  e('🗄️', 'File Cabinet', 'Objects', ['filing', 'storage']),
  e('📋', 'Clipboard', 'Objects', ['copy', 'paste', 'checklist']),
  e('📁', 'File Folder', 'Objects', ['directory', 'collection']),
  e('📂', 'Open File Folder', 'Objects', ['directory', 'browse']),
  e('🗎', 'Document', 'Objects', ['file']),
  e('🗞️', 'Rolled-Up Newspaper', 'Objects', ['news']),
  e('📰', 'Newspaper', 'Objects', ['press', 'news']),
  e('📓', 'Notebook', 'Objects', ['journal', 'write']),
  e('📕', 'Closed Book', 'Objects', ['read', 'book']),
  e('📖', 'Open Book', 'Objects', ['reading', 'literature']),
  e('📗', 'Green Book', 'Objects', ['book']),
  e('📘', 'Blue Book', 'Objects', ['book']),
  e('📙', 'Orange Book', 'Objects', ['book']),
  e('📚', 'Books', 'Objects', ['library', 'study', 'education']),
  e('🏷️', 'Label', 'Objects', ['tag', 'price', 'category']),
  e('🔖', 'Bookmark', 'Objects', ['favorite', 'save']),
  e('🔗', 'Link', 'Objects', ['hyperlink', 'url', 'connect']),
  e('📎', 'Paperclip', 'Objects', ['attachment', 'clip']),
  e('🖇️', 'Linked Paperclips', 'Objects', ['attached']),
  e('📐', 'Triangular Ruler', 'Objects', ['measure', 'math', 'geometry']),
  e('📏', 'Straight Ruler', 'Objects', ['measure']),
  e('🧮', 'Abacus', 'Objects', ['math', 'calculate']),
  e('📌', 'Pushpin', 'Objects', ['pin', 'notice']),
  e('📍', 'Round Pushpin', 'Objects', ['location', 'map', 'pin']),
  e('✂️', 'Scissors', 'Objects', ['cut', 'craft']),
  e('🖊️', 'Pen', 'Objects', ['write', 'ink']),
  e('🖋️', 'Fountain Pen', 'Objects', ['signature', 'fancy']),
  e('✒️', 'Black Nib', 'Objects', ['quill', 'pen']),
  e('🖌️', 'Paintbrush', 'Objects', ['art', 'paint']),
  e('🖍️', 'Crayon', 'Objects', ['draw', 'color']),
  e('📝', 'Memo', 'Objects', ['note', 'write', 'document']),
  e('✏️', 'Pencil', 'Objects', ['write', 'edit', 'draft']),
  e('🔍', 'Magnifying Glass Tilted Left', 'Objects', ['search', 'find', 'lookup']),
  e('🔎', 'Magnifying Glass Tilted Right', 'Objects', ['search', 'inspect']),
  e('💻', 'Laptop', 'Objects', ['computer', 'pc', 'code', 'tech']),
  e('🖥️', 'Desktop Computer', 'Objects', ['pc', 'monitor', 'screen']),
  e('🖨️', 'Printer', 'Objects', ['print', 'paper']),
  e('⌨️', 'Keyboard', 'Objects', ['typing', 'keys']),
  e('🖱️', 'Computer Mouse', 'Objects', ['click']),
  e('🖲️', 'Trackball', 'Objects', ['mouse']),
  e('💽', 'Computer Disk', 'Objects', ['minidisc']),
  e('💾', 'Floppy Disk', 'Objects', ['save', 'disk', 'storage']),
  e('💿', 'Optical Disk', 'Objects', ['cd', 'dvd']),
  e('📀', 'DVD', 'Objects', ['disc', 'movie']),
  e('📱', 'Mobile Phone', 'Objects', ['smartphone', 'cell', 'iphone']),
  e('📲', 'Mobile Phone with Arrow', 'Objects', ['call', 'message']),
  e('☎️', 'Telephone', 'Objects', ['phone', 'call']),
  e('📞', 'Telephone Receiver', 'Objects', ['call']),
  e('📟', 'Pager', 'Objects', ['beeper']),
  e('📠', 'Fax Machine', 'Objects', ['fax']),
  e('📺', 'Television', 'Objects', ['tv', 'screen']),
  e('📻', 'Radio', 'Objects', ['broadcast']),
  e('🎙️', 'Studio Microphone', 'Objects', ['podcast', 'record']),
  e('🎚️', 'Level Slider', 'Objects', ['volume', 'audio']),
  e('🎛️', 'Control Knobs', 'Objects', ['mixer', 'audio']),
  e('🧭', 'Compass', 'Objects', ['navigation', 'direction']),
  e('⏱️', 'Stopwatch', 'Objects', ['time', 'timer']),
  e('⏲️', 'Timer Clock', 'Objects', ['kitchen']),
  e('⏰', 'Alarm Clock', 'Objects', ['wake', 'time']),
  e('🕰️', 'Mantelpiece Clock', 'Objects', ['vintage']),
  e('⏳', 'Hourglass Done', 'Objects', ['time', 'sand']),
  e('⌛', 'Hourglass Not Done', 'Objects', ['wait', 'loading']),
  e('📷', 'Camera', 'Objects', ['photo', 'snapshot']),
  e('📸', 'Camera with Flash', 'Objects', ['photo']),
  e('📹', 'Video Camera', 'Objects', ['record', 'movie']),
  e('📼', 'Videocassette', 'Objects', ['vhs', 'tape']),
  e('🔋', 'Battery', 'Objects', ['power', 'charge']),
  e('🪫', 'Low Battery', 'Objects', ['dead']),
  e('🔌', 'Electric Plug', 'Objects', ['power', 'cable']),
  e('🪙', 'Coin', 'Objects', ['money', 'gold', 'currency']),
  e('💰', 'Money Bag', 'Objects', ['cash', 'wealth', 'dollar']),
  e('💵', 'Dollar Banknote', 'Objects', ['cash', 'currency']),
  e('💳', 'Credit Card', 'Objects', ['pay', 'visa', 'mastercard']),
  e('💎', 'Gem Stone', 'Objects', ['diamond', 'jewelry', 'valuable']),

  // ── Symbols ──
  e('🏧', 'ATM Sign', 'Symbols', ['bank']),
  e('🚮', 'Litter in Bin Sign', 'Symbols', ['trash']),
  e('🚰', 'Potable Water', 'Symbols', ['drink']),
  e('♿', 'Wheelchair Symbol', 'Symbols', ['accessible']),
  e('🚹', 'Men’s Room', 'Symbols', ['restroom']),
  e('🚺', 'Women’s Room', 'Symbols', ['restroom']),
  e('🚻', 'Restroom', 'Symbols', ['toilet', 'wc']),
  e('🚼', 'Baby Symbol', 'Symbols', ['nursery']),
  e('🚾', 'Water Closet', 'Symbols', ['toilet', 'restroom']),
  e('🛂', 'Passport Control', 'Symbols', ['customs']),
  e('🛃', 'Customs', 'Symbols', ['airport']),
  e('🛄', 'Baggage Claim', 'Symbols', ['luggage']),
  e('🛅', 'Left Luggage', 'Symbols', ['storage']),
  e('⚠️', 'Warning', 'Symbols', ['alert', 'caution', 'danger']),
  e('🚸', 'Children Crossing', 'Symbols', ['school']),
  e('⛔', 'No Entry', 'Symbols', ['stop', 'forbidden', 'denied']),
  e('🚫', 'Prohibited', 'Symbols', ['no', 'ban', 'not allowed']),
  e('🚳', 'No Bicycles', 'Symbols', ['forbidden']),
  e('🚭', 'No Smoking', 'Symbols', ['forbidden']),
  e('🚯', 'No Littering', 'Symbols', ['forbidden']),
  e('🚱', 'Non-Potable Water', 'Symbols', ['forbidden']),
  e('🚷', 'No Pedestrians', 'Symbols', ['forbidden']),
  e('📵', 'No Mobile Phones', 'Symbols', ['silent']),
  e('🔞', 'No One Under Eighteen', 'Symbols', ['18', 'adult']),
  e('☢️', 'Radioactive', 'Symbols', ['nuclear', 'hazard']),
  e('☣️', 'Biohazard', 'Symbols', ['danger']),
  e('⬆️', 'Up Arrow', 'Symbols', ['arrow', 'north']),
  e('↗️', 'Up-Right Arrow', 'Symbols', ['arrow']),
  e('➡️', 'Right Arrow', 'Symbols', ['arrow', 'east']),
  e('↘️', 'Down-Right Arrow', 'Symbols', ['arrow']),
  e('⬇️', 'Down Arrow', 'Symbols', ['arrow', 'south']),
  e('↙️', 'Down-Left Arrow', 'Symbols', ['arrow']),
  e('⬅️', 'Left Arrow', 'Symbols', ['arrow', 'west']),
  e('↖️', 'Up-Left Arrow', 'Symbols', ['arrow']),
  e('↕️', 'Up-Down Arrow', 'Symbols', ['arrow']),
  e('↔️', 'Left-Right Arrow', 'Symbols', ['arrow']),
  e('↩️', 'Right Arrow Curving Left', 'Symbols', ['return', 'undo']),
  e('↪️', 'Left Arrow Curving Right', 'Symbols', ['redo']),
  e('⤴️', 'Right Arrow Curving Up', 'Symbols', ['arrow']),
  e('⤵️', 'Right Arrow Curving Down', 'Symbols', ['arrow']),
  e('🔃', 'Clockwise Vertical Arrows', 'Symbols', ['reload', 'refresh', 'sync']),
  e('🔄', 'Counterclockwise Arrows Button', 'Symbols', ['repeat', 'cycle']),
  e('🔙', 'Back Arrow', 'Symbols', ['back']),
  e('🔚', 'End Arrow', 'Symbols', ['end']),
  e('🔛', 'On! Arrow', 'Symbols', ['on']),
  e('🔜', 'Soon Arrow', 'Symbols', ['soon']),
  e('🔝', 'Top Arrow', 'Symbols', ['top']),
  e('🛐', 'Place of Worship', 'Symbols', ['religion']),
  e('⚛️', 'Atom Symbol', 'Symbols', ['science', 'physics', 'react']),
  e('🕉️', 'Om', 'Symbols', ['hindu']),
  e('✡️', 'Star of David', 'Symbols', ['jewish']),
  e('☸️', 'Wheel of Dharma', 'Symbols', ['buddhist']),
  e('☯️', 'Yin Yang', 'Symbols', ['balance', 'dao']),
  e('✝️', 'Latin Cross', 'Symbols', ['christian']),
  e('☦️', 'Orthodox Cross', 'Symbols', ['christian']),
  e('☪️', 'Star and Crescent', 'Symbols', ['islam']),
  e('☮️', 'Peace Symbol', 'Symbols', ['peace']),
  e('🕎', 'Menorah', 'Symbols', ['hanukkah']),
  e('🔯', 'Dotted Six-Pointed Star', 'Symbols', ['star']),
  e('♈', 'Aries', 'Symbols', ['zodiac']),
  e('♉', 'Taurus', 'Symbols', ['zodiac']),
  e('♊', 'Gemini', 'Symbols', ['zodiac']),
  e('♋', 'Cancer', 'Symbols', ['zodiac']),
  e('♌', 'Leo', 'Symbols', ['zodiac']),
  e('♍', 'Virgo', 'Symbols', ['zodiac']),
  e('♎', 'Libra', 'Symbols', ['zodiac']),
  e('♏', 'Scorpio', 'Symbols', ['zodiac']),
  e('♐', 'Sagittarius', 'Symbols', ['zodiac']),
  e('♑', 'Capricorn', 'Symbols', ['zodiac']),
  e('♒', 'Aquarius', 'Symbols', ['zodiac']),
  e('♓', 'Pisces', 'Symbols', ['zodiac']),
  e('⛎', 'Ophiuchus', 'Symbols', ['zodiac']),
  e('🔀', 'Shuffle Tracks Button', 'Symbols', ['random']),
  e('🔁', 'Repeat Button', 'Symbols', ['loop']),
  e('🔂', 'Repeat Single Button', 'Symbols', ['once']),
  e('▶️', 'Play Button', 'Symbols', ['start', 'run']),
  e('⏩', 'Fast-Forward Button', 'Symbols', ['speed']),
  e('⏭️', 'Next Track Button', 'Symbols', ['skip']),
  e('⏯️', 'Play or Pause Button', 'Symbols', ['media']),
  e('◀️', 'Reverse Button', 'Symbols', ['back']),
  e('⏪', 'Fast Reverse Button', 'Symbols', ['rewind']),
  e('⏮️', 'Last Track Button', 'Symbols', ['previous']),
  e('🔼', 'Upwards Button', 'Symbols', ['triangle']),
  e('⏫', 'Fast Up Button', 'Symbols', ['double']),
  e('🔽', 'Downwards Button', 'Symbols', ['triangle']),
  e('⏬', 'Fast Down Button', 'Symbols', ['double']),
  e('⏸️', 'Pause Button', 'Symbols', ['stop']),
  e('⏹️', 'Stop Button', 'Symbols', ['halt']),
  e('⏺️', 'Record Button', 'Symbols', ['circle']),
  e('⏏️', 'Eject Button', 'Symbols', ['disc']),
  e('🎦', 'Cinema', 'Symbols', ['film', 'movie']),
  e('🔅', 'Dim Button', 'Symbols', ['brightness']),
  e('🔆', 'Bright Button', 'Symbols', ['light']),
  e('📶', 'Antenna Bars', 'Symbols', ['wifi', 'signal', 'reception']),
  e('📳', 'Vibration Mode', 'Symbols', ['phone']),
  e('📴', 'Mobile Phone Off', 'Symbols', ['power']),
  e('♀️', 'Female Sign', 'Symbols', ['woman', 'gender']),
  e('♂️', 'Male Sign', 'Symbols', ['man', 'gender']),
  e('⚧️', 'Transgender Symbol', 'Symbols', ['gender']),
  e('✖️', 'Multiply', 'Symbols', ['math', 'x']),
  e('➕', 'Plus', 'Symbols', ['add', 'math']),
  e('➖', 'Minus', 'Symbols', ['subtract', 'math']),
  e('➗', 'Divide', 'Symbols', ['math']),
  e('🟰', 'Heavy Equals Sign', 'Symbols', ['math', 'same']),
  e('♾️', 'Infinity', 'Symbols', ['forever', 'loop']),
  e('‼️', 'Double Exclamation Mark', 'Symbols', ['bang', 'alert']),
  e('⁉️', 'Exclamation Question Mark', 'Symbols', ['interrobang']),
  e('❓', 'Red Question Mark', 'Symbols', ['help', 'query', 'ask']),
  e('❔', 'White Question Mark', 'Symbols', ['help', 'query']),
  e('❕', 'White Exclamation Mark', 'Symbols', ['alert']),
  e('❗', 'Red Exclamation Mark', 'Symbols', ['danger', 'important', 'alert']),
  e('〰️', 'Wavy Dash', 'Symbols', ['wave']),
  e('💱', 'Currency Exchange', 'Symbols', ['forex', 'money']),
  e('💲', 'Heavy Dollar Sign', 'Symbols', ['money', 'usd']),
  e('⚕️', 'Medical Symbol', 'Symbols', ['health', 'caduceus']),
  e('♻️', 'Recycling Symbol', 'Symbols', ['green', 'recycle', 'eco']),
  e('⚜️', 'Fleur-de-lis', 'Symbols', ['french', 'scouts']),
  e('🔱', 'Trident Emblem', 'Symbols', ['poseidon']),
  e('📛', 'Name Badge', 'Symbols', ['tag']),
  e('🔰', 'Japanese Symbol for Beginner', 'Symbols', ['shoshinsha', 'newbie']),
  e('⭕', 'Hollow Red Circle', 'Symbols', ['correct', 'circle']),
  e('✅', 'Check Mark Button', 'Symbols', ['done', 'ok', 'verified', 'complete', 'success']),
  e('☑️', 'Check Box with Check', 'Symbols', ['task', 'todo']),
  e('✔️', 'Check Mark', 'Symbols', ['yes', 'correct']),
  e('❌', 'Cross Mark', 'Symbols', ['no', 'wrong', 'cancel', 'error']),
  e('❎', 'Cross Mark Button', 'Symbols', ['cancel']),
  e('➰', 'Curly Loop', 'Symbols', ['curl']),
  e('➿', 'Double Curly Loop', 'Symbols', ['voicemail']),
  e('〽️', 'Part Alternation Mark', 'Symbols', ['m']),
  e('✳️', 'Eight-Spoked Asterisk', 'Symbols', ['star']),
  e('✴️', 'Eight-Pointed Star', 'Symbols', ['star']),
  e('❇️', 'Sparkle', 'Symbols', ['glitter']),
  e('©️', 'Copyright', 'Symbols', ['legal']),
  e('®️', 'Registered', 'Symbols', ['trademark']),
  e('™️', 'Trade Mark', 'Symbols', ['trademark', 'brand']),
  e('🔴', 'Red Circle', 'Symbols', ['dot']),
  e('🟠', 'Orange Circle', 'Symbols', ['dot']),
  e('🟡', 'Yellow Circle', 'Symbols', ['dot']),
  e('🟢', 'Green Circle', 'Symbols', ['dot', 'online', 'active']),
  e('🔵', 'Blue Circle', 'Symbols', ['dot']),
  e('🟣', 'Purple Circle', 'Symbols', ['dot']),
  e('🟤', 'Brown Circle', 'Symbols', ['dot']),
  e('⚫', 'Black Circle', 'Symbols', ['dot']),
  e('⚪', 'White Circle', 'Symbols', ['dot']),
  e('🟥', 'Red Square', 'Symbols', ['shape']),
  e('🟧', 'Orange Square', 'Symbols', ['shape']),
  e('🟨', 'Yellow Square', 'Symbols', ['shape']),
  e('🟩', 'Green Square', 'Symbols', ['shape']),
  e('🟦', 'Blue Square', 'Symbols', ['shape']),
  e('🟪', 'Purple Square', 'Symbols', ['shape']),
  e('🟫', 'Brown Square', 'Symbols', ['shape']),
  e('⬛', 'Black Large Square', 'Symbols', ['shape']),
  e('⬜', 'White Large Square', 'Symbols', ['shape']),
  e('🏁', 'Chequered Flag', 'Symbols', ['finish', 'racing']),
  e('🚩', 'Triangular Flag', 'Symbols', ['red flag', 'mark', 'goal']),
  e('🎌', 'Crossed Flags', 'Symbols', ['japan']),
  e('🏴', 'Black Flag', 'Symbols', ['pirate']),
  e('🏳️', 'White Flag', 'Symbols', ['surrender', 'peace']),
  e('🏳️‍🌈', 'Rainbow Flag', 'Symbols', ['pride', 'lgbtq']),
  e('🏳️‍⚧️', 'Transgender Flag', 'Symbols', ['pride']),
  e('🏴‍☠️', 'Pirate Flag', 'Symbols', ['jolly roger', 'skull']),
];

export const EMOJI_MAP = new Map<string, EmojiDefinition>(
  EMOJI_CATALOG.map((item) => [item.char, item])
);
