import { ThemeDefinition } from '../types';

export const NOETHER_LIGHT_THEME: ThemeDefinition = {
  id: 'noether-light',
  name: 'Noether Light',
  description: 'Clean, crisp, modern neutral light theme with pure white canvas, zinc neutral surfaces, and high-contrast typography.',
  author: 'Noether Core',
  type: 'light',
  isPreinstalled: true,
  isBuiltIn: true,
  hasGradient: false,
  previewColors: ['#f4f4f5', '#f8f9fa', '#ffffff', '#eb584d'],
  variables: {
    bgApp: '#f4f4f5',
    bgTopBar: '#f4f4f5',
    bgRibbon: '#eceff1',
    bgSidebar: '#f8f9fa',
    bgSidebarHover: '#e4e4e7',
    bgSidebarActive: '#d4d4d8',
    bgMain: '#ffffff',
    bgCard: '#ffffff',
    bgCardHover: '#f4f4f5',
    bgPopover: '#ffffff',
    bgInput: '#ffffff',
    bgInputFocus: '#ffffff',
    bgTabActive: '#ffffff',
    bgTabHover: '#f4f4f5',
    bgTabInactive: 'transparent',
    tabCornerFill: '#ffffff',
    tabCornerHoverFill: '#f4f4f5',
    bgStatusBar: '#f4f4f5',
    borderSubtle: '#f0f0f2',
    borderBase: '#e4e4e7',
    borderStrong: '#cbd5e1',
    textPrimary: '#09090b',
    textSecondary: '#27272a',
    textMuted: '#52525b',
    textFaint: '#71717a',
    accent: '#eb584d',
    accentHover: '#d94338',
    accentActive: '#b83228',
    accentSubtle: 'rgba(235, 88, 77, 0.12)',
    accentGradient: 'linear-gradient(135deg, #eb584d 0%, #f07167 100%)',
    selectionBg: '#e4e4e7',
    selectionText: '#09090b',
    codeBg: '#f4f4f5',
    codeText: '#09090b',
    tooltipBg: '#18181b',
    tooltipText: '#fafafa',
    tooltipMuted: '#a1a1aa',
    tooltipBorder: '#27272a',
    shadow1: '0 1px 2px 0 rgba(0, 0, 0, 0.03)',
    shadow2: '0 4px 12px -2px rgba(0, 0, 0, 0.06), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
    shadow3: '0 10px 24px -4px rgba(0, 0, 0, 0.08), 0 4px 8px -2px rgba(0, 0, 0, 0.04)',
  },
};

export const noetherLight = NOETHER_LIGHT_THEME;
